### PR TITLE
Fix bugs

### LINKED ISSUE #70: Bug: need state in App with userId/Ratings to be able to delete user's movie rating

### LINKED ISSUE #71: Bug: DELETE - button click - unexpected end of JSON

### LINKED ISSUE #72: Bug: MoviePage user rating starts as "not yet rated" even if it has a rating
take in App.state as prop

### PR DESCRIPTION
**Pull request by BlakeDonn**
# Rotten Tomatillos PR template
### What's this PR do?  
- Fixes bugs related to logic that depends on a user being logged in
- Displays user rating based on submitted rating
- Asks user to delete current rating rather than have a delete rating button 
- Adjusts data flow in app to better represent current state

### Where should the reviewer start?  
- Start by launching the App 
 
### How should this be manually tested?  

- Test all user interactions, not logged in user, logged in , updated, etc.
- Log out, log in etc.  

### Any background context you want to provide?  

-Still trying to figure out how to handle the preview cards, adding state will probably be easy enough

### What are the relevant tickets?  
closes #72    
closes #71 
closes #70

### CODE REVIEW

File: src/CardsContainer/CardsContainer.js [hunk 1]
```diff
@@ -2,13 +2,15 @@ import React from "react";
...
+  let ratedMovie;
   let pCards = props.movies.map((movie) => {
-    return (
-      <PreviewCard
-        history={props.history}
-        {...movie}
-      />
-    );
+    if (props.userRatings) {
+      ratedMovie = props.userRatings.find((x) => x.movie_id === movie.id);
```
Comment (hannakim91) [inline src/CardsContainer/CardsContainer.js:8]: Probably should rename this variable `x`

**Review by hannakim91 — APPROVED** [review]
Thanks for finishing up fixing these bugs from adding the user rating feature!

File: src/MoviePage/MoviePage.js [hunk 2]
```diff
@@ -1,21 +1,63 @@
...
+  };
+  submitRating = async (e) => {
+    e.preventDefault();
+    let response = await postUserRating(
+      this.state.userId,
+      this.state.displayedRating,
+      this.state.movie.id
+    );
+    if (response.error) {
+      let userInput = window.confirm(
```
Comment (hannakim91) [inline src/MoviePage/MoviePage.js:43]: Cool, I've never seen this type of feature before!

File: src/MoviePage/MoviePage.js [hunk 3]
```diff
@@ -1,21 +1,63 @@
...
+      } else {
+        this.setState({userRating: this.state.displayedRating});
+      }
+    } else {
+      this.setState({userRating: this.state.displayedRating});
+    }
+
+    console.log(response);
+  };
+  deleteMovie = () => {
```
Comment (hannakim91) [inline src/MoviePage/MoviePage.js:57]: Think this was a good refactor - it will likely be better UX to not have so many buttons around one feature

File: src/PreviewCard/PreviewCard.js [hunk 4]
```diff
@@ -11,7 +18,9 @@ const PreviewCard = ({history, id, poster_path, title, average_rating}) => {
       <img src={poster_path} alt={`poster of ${title}`}></img>
       <h3 className="movie-title">{title}</h3>
       <p className="avg-rating">{average_rating}</p>
-      <p className="user-rating">"Your rating"</p>
+      <p className="user-rating">
+        {userRating ? `Your rating: ${userRating}` : "Click for more details"}{" "}
```
Comment (hannakim91) [inline src/PreviewCard/PreviewCard.js:22]: Maybe just rewording the ternary (`click for more details`) for better UX
